\ Control an LED on VIA's pin PA0

6001 VALUE PORTA
6003 VALUE DDRA

2000 VALUE TEMPO    \ wait time

\ PA0 is output
DDRA C@ 1 OR DDRA C!

: off PORTA C@ FE AND PORTA C! ;
: on PORTA C@ 1 OR PORTA C! ;
: t PORTA C@ 1 XOR PORTA C! ;

: WAIT 0 DO LOOP ;

: BLINK 10 0 DO t TEMPO WAIT LOOP ;

: FAST 500 TO TEMPO ;
: MEDIUM 1500 TO TEMPO ;
: SLOW 2500 TO TEMPO ;

FAST BLINK